using System;

namespace projecteuler
{
    class Program
    {
        static void Main(string[] args)
        {
          //  multiplesOfThreeOrFive();
          evenFibonacciNumbers();
        }

        public static void multiplesOfThreeOrFive()
        {
        // If we list all the natural numbers below 10 that are multiples of 3 or 5,
        // we get 3, 5, 6 and 9. The sum of these multiples is 23.
        // Find the sum of all the multiples of 3 or 5 below 1000.
        int sum = 0;
        for(int i = 0; i < 1000; i++)
        {
            if(i % 3 == 0 || i % 5 == 0)
            {
                sum += i;
            }
        }
            Console.WriteLine(sum);
        }

        public static void evenFibonacciNumbers()
        {
            /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms.
            By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence whose values do not exceed four million,
            find the sum of the even-valued terms.
            */

            for(int i = 2; i < 4000000; i++)
            {
                if(i % 2 == 0)
                 Console.WriteLine(fib(i));
            }
        }

            public static long fib(long n)
             {
                if ((n == 0) || (n == 1))
                    return n;
                else
                    return fib(n - 1) + fib(n - 2);
            }
    }
}
